// <auto-generated />
using DraftDatastore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DraftDatastore.Persistence.Migrations;

[DbContext(typeof(DraftDatastoreDbContext))]
[Migration("20260912090000_AddLiveAuctionHubPhase2")]
partial class AddLiveAuctionHubPhase2
{
    // The operational schema is defined by the migration's Up method. EF uses the
    // migration attribute to discover and apply it; the canonical model remains in
    // the DbContext and snapshot.
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "8.0.20");
    }
}
