using DraftDatastore.Domain.Entities;
using FluentValidation;

namespace DraftDatastore.Application.Players;

public sealed record PlayerUpsertRequest(string FullName, int NationalityId, int PlayingEraId, string ShortDescription, int OverallRank, decimal GoalCreditPoints, decimal AssistCreditPoints, decimal DefensiveCreditPoints, string? TransfermarktUrl, string? WikipediaUrl, IReadOnlyCollection<string> Aliases, IReadOnlyCollection<int> PositionIds, int PrimaryPositionId);
public sealed record PlayerPatchRequest(string? FullName = null, int? NationalityId = null, int? PlayingEraId = null, string? ShortDescription = null, int? OverallRank = null, decimal? GoalCreditPoints = null, decimal? AssistCreditPoints = null, decimal? DefensiveCreditPoints = null, string? TransfermarktUrl = null, string? WikipediaUrl = null, IReadOnlyCollection<string>? Aliases = null, IReadOnlyCollection<int>? PositionIds = null, int? PrimaryPositionId = null);
public sealed record PlayerSearchRequest(int PageNumber = 1, int PageSize = 25, string? Search = null, int? PositionId = null, int? NationalityId = null, int? PlayingEraId = null, int? ActiveFromYear = null, int? ActiveToYear = null, int? Rank = null, string SortBy = "rank", bool Descending = false);
public sealed record PlayerResponse(Guid Id, string FullName, string Nationality, string PlayingEra, IReadOnlyCollection<string> Positions, IReadOnlyCollection<string> Aliases, string ShortDescription, int OverallRank, decimal GoalCreditPoints, decimal AssistCreditPoints, decimal DefensiveCreditPoints, string? TransfermarktUrl, string? WikipediaUrl, string? PrimaryImageUrl, DateTimeOffset CreatedAtUtc, DateTimeOffset? UpdatedAtUtc);
public sealed record PagedResult<T>(IReadOnlyCollection<T> Items, int PageNumber, int PageSize, int TotalCount);
public interface IPlayerService { Task<PagedResult<PlayerResponse>> SearchAsync(PlayerSearchRequest request, CancellationToken ct); Task<PlayerResponse?> GetAsync(Guid id,CancellationToken ct); Task<PlayerResponse> CreateAsync(PlayerUpsertRequest request,CancellationToken ct); Task<PlayerResponse?> UpdateAsync(Guid id,PlayerUpsertRequest request,CancellationToken ct); Task<PlayerResponse?> PatchAsync(Guid id,PlayerPatchRequest request,CancellationToken ct); Task<bool> DeleteAsync(Guid id,CancellationToken ct); Task<bool> RestoreAsync(Guid id,CancellationToken ct); }
public interface IPlayerRepository { Task<PagedResult<Player>> SearchAsync(PlayerSearchRequest request,CancellationToken ct); Task<Player?> GetAsync(Guid id,bool includeDeleted,CancellationToken ct); Task AddAsync(Player player,CancellationToken ct); Task SaveAsync(CancellationToken ct); }
public sealed class PlayerUpsertRequestValidator : AbstractValidator<PlayerUpsertRequest> { public PlayerUpsertRequestValidator() { RuleFor(x=>x.FullName).NotEmpty().MaximumLength(160); RuleFor(x=>x.NationalityId).GreaterThan(0); RuleFor(x=>x.PlayingEraId).GreaterThan(0); RuleFor(x=>x.ShortDescription).NotEmpty().MaximumLength(2000); RuleFor(x=>x.OverallRank).GreaterThan(0); RuleFor(x=>x.GoalCreditPoints).GreaterThanOrEqualTo(0); RuleFor(x=>x.AssistCreditPoints).GreaterThanOrEqualTo(0); RuleFor(x=>x.DefensiveCreditPoints).GreaterThanOrEqualTo(0); RuleFor(x=>x.PositionIds).NotEmpty(); RuleFor(x=>x).Must(x=>x.PositionIds.Contains(x.PrimaryPositionId)).WithMessage("PrimaryPositionId must be included in PositionIds."); } }
public sealed class PlayerSearchRequestValidator : AbstractValidator<PlayerSearchRequest> { public PlayerSearchRequestValidator() { RuleFor(x=>x.PageNumber).GreaterThan(0); RuleFor(x=>x.PageSize).InclusiveBetween(1,100); RuleFor(x=>x.SortBy).Must(x=>new[]{"rank","name","goalCredit","assistCredit","defensiveCredit"}.Contains(x,StringComparer.OrdinalIgnoreCase)).WithMessage("SortBy is invalid."); } }
