using DraftDatastore.Domain.Entities;
using DraftDatastore.Persistence;
using Microsoft.EntityFrameworkCore;

var apply = args.Contains("--apply", StringComparer.OrdinalIgnoreCase);
var targets = new[]
{
    new Target("Cristiano Ronaldo", "Cristiano Ronaldo", 1, null, true), new Target("George Best", "George Best", 2, null, true), new Target("Thierry Henry", "Titi", 3, "https://www.transfermarkt.co.in/thierry-henry/profil/spieler/3207"), new Target("Dragan Džajić", "The Magic Dragan", 4, "https://www.transfermarkt.co.in/dragan-dzajic/profil/spieler/145124"), new Target("Ronaldinho", "R10", 4, "https://www.transfermarkt.co.in/ronaldinho/profil/spieler/3373"), new Target("Hristo Stoichkov", "The Dagger", 5, "https://www.transfermarkt.co.in/hristo-stoichkov/profil/spieler/7938"), new Target("Roberto Rivellino", "Rivelino", 5, "https://www.transfermarkt.co.in/rivellino/profil/spieler/10201"), new Target("Pavel Nedvěd", "Czech Fury", 5, "https://www.transfermarkt.co.in/pavel-nedved/profil/spieler/3603"), new Target("Paco Gento", "Paco Gento", 6, "https://www.transfermarkt.co.in/paco-gento/profil/spieler/170723"), new Target("Ryan Giggs", "Giggsy", 6, "https://www.transfermarkt.co.in/ryan-giggs/profil/spieler/3406"), new Target("Robert Pirès", "Robert Emmanuel", 7, "https://www.transfermarkt.co.in/robert-pires/profil/spieler/3185"), new Target("Franck Ribéry", "Francky", 7, "https://www.transfermarkt.co.in/franck-ribery/profil/spieler/22068"), new Target("Valentino Mazzola", "Valentino Mazzola", 8, "https://www.transfermarkt.co.in/valentino-mazzola/profil/spieler/291722"), new Target("Zoltán Czibor", "Bolond", 8, "https://www.transfermarkt.co.in/zoltan-czibor/profil/spieler/136479"), new Target("Rob Rensenbrink", "The Snake Man", 9, "https://www.transfermarkt.co.in/rob-rensenbrink/profil/spieler/135644"), new Target("Oleg Blokhin", "Oleg Volodymyrovych", 9, "https://www.transfermarkt.co.in/oleg-blokhin/profil/spieler/117372"), new Target("Tom Finney", "Sir Tom Finney", 10, "https://www.transfermarkt.co.in/sir-tom-finney/profil/spieler/215277"), new Target("Raimundo Orsi", "Mumo Orsi", 10, "https://www.transfermarkt.co.in/raimundo-orsi/profil/spieler/237906")
};
var options = new DbContextOptionsBuilder<DraftDatastoreDbContext>().UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=DraftDatastore;Trusted_Connection=True;TrustServerCertificate=True").Options;
await using var db = new DraftDatastoreDbContext(options); var players = await db.Players.Include(player => player.Aliases).Include(player => player.PlayerPositions).ToListAsync(); var leftWing = await db.Positions.SingleAsync(position => position.Code == "LW"); var resolved = new List<(Target Target, Player Player)>(); var unresolved = new List<string>();
foreach (var target in targets) { var matches = players.Where(player => Matches(player, target.Lookup)).ToList(); if (matches.Count != 1) unresolved.Add($"{target.Name} ({matches.Count} matches)"); else resolved.Add((target, matches[0])); }
if (unresolved.Count > 0) { Console.Error.WriteLine("No changes were made because these targets were not uniquely resolved:"); foreach (var target in unresolved) Console.Error.WriteLine($"- {target}"); return 1; }
var approvedIds = resolved.Select(item => item.Player.Id).ToHashSet(); var currentEntries = players.Where(player => player.PlayerPositions.Any(position => position.PositionId == leftWing.Id)).OrderBy(player => player.FullName).ToList(); var removals = currentEntries.Where(player => !approvedIds.Contains(player.Id)).ToList(); var additions = resolved.Where(item => item.Player.PlayerPositions.All(position => position.PositionId != leftWing.Id)).ToList(); var rankUpdates = resolved.Where(item => item.Player.PlayerPositions.SingleOrDefault(position => position.PositionId == leftWing.Id)?.OverallRank != item.Target.Rank).ToList(); var linkUpdates = resolved.Where(item => item.Target.TransfermarktUrl is not null && !string.Equals(item.Player.TransfermarktUrl, item.Target.TransfermarktUrl, StringComparison.Ordinal)).ToList();
Console.WriteLine($"Left Wing catalogue review: {resolved.Count} approved players, {currentEntries.Count} current entries."); Console.WriteLine($"Will remove Left Wing from: {(removals.Count == 0 ? "none" : string.Join(", ", removals.Select(player => player.FullName)))}"); Console.WriteLine($"Will add Left Wing to: {(additions.Count == 0 ? "none" : string.Join(", ", additions.Select(item => item.Player.FullName)))}"); Console.WriteLine($"Will set Left Wing-specific ranks for: {(rankUpdates.Count == 0 ? "none" : string.Join(", ", rankUpdates.Select(item => $"{item.Player.FullName} #{item.Target.Rank}")))}"); Console.WriteLine($"Will update Transfermarkt links for: {(linkUpdates.Count == 0 ? "none" : string.Join(", ", linkUpdates.Select(item => item.Player.FullName)))}"); Console.WriteLine("Exception entries retain all of their other position mappings.");
if (!apply) { Console.WriteLine("Dry run complete. Re-run with --apply to save these changes."); return 0; }
await using var transaction = await db.Database.BeginTransactionAsync(); foreach (var player in removals) db.PlayerPositions.Remove(player.PlayerPositions.Single(position => position.PositionId == leftWing.Id)); foreach (var (target, player) in resolved) { var mapping = player.PlayerPositions.SingleOrDefault(position => position.PositionId == leftWing.Id); if (mapping is null) { mapping = new PlayerPosition { PlayerId = player.Id, PositionId = leftWing.Id, IsPrimary = false }; db.PlayerPositions.Add(mapping); } mapping.OverallRank = target.Rank; if (target.TransfermarktUrl is not null) player.TransfermarktUrl = target.TransfermarktUrl; } await db.SaveChangesAsync(); await transaction.CommitAsync(); Console.WriteLine("Left Wing catalogue, ranks, and Transfermarkt links updated successfully."); return 0;
static bool Matches(Player player, string lookup) => string.Equals(player.FullName, lookup, StringComparison.OrdinalIgnoreCase) || player.Aliases.Any(alias => string.Equals(alias.Alias, lookup, StringComparison.OrdinalIgnoreCase)) || player.FullName.Contains(lookup, StringComparison.OrdinalIgnoreCase) || player.Aliases.Any(alias => alias.Alias.Contains(lookup, StringComparison.OrdinalIgnoreCase));
sealed record Target(string Name, string Lookup, int Rank, string? TransfermarktUrl, bool IsException = false);
