<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\API\DraftDatastore\DraftDatastore.Persistence\DraftDatastore.Persistence.csproj" /><ProjectReference Include="..\API\DraftDatastore\DraftDatastore.Domain\DraftDatastore.Domain.csproj" /></ItemGroup>
</Project>
