using DraftDatastore.Domain.Entities;
using DraftDatastore.Persistence;
using Microsoft.EntityFrameworkCore;

var apply = args.Contains("--apply", StringComparer.OrdinalIgnoreCase);
var targets = new[]
{
    new Target("Diego Maradona", "D10S", 1, "https://www.transfermarkt.com/diego-maradona/profil/spieler/8024"), new Target("Michel Platini", "Platoche", 2, "https://www.transfermarkt.com/michel-platini/profil/spieler/88994"), new Target("Zinedine Zidane", "Zizou", 3, "https://www.transfermarkt.com/zinedine-zidane/profil/spieler/3111"), new Target("Alfredo Di Stéfano", "ADS", 3, "https://www.transfermarkt.com/alfredo-di-stefano/profil/spieler/135778"), new Target("Zico", "Galinho de Quintino", 4, "https://www.transfermarkt.com/zico/profil/spieler/117619"), new Target("Bobby Charlton", "SBC", 4, "https://www.transfermarkt.com/sir-bobby-charlton/profil/spieler/174874"), new Target("Rivaldo", "Rivaldo", 5, "https://www.transfermarkt.com/rivaldo/profil/spieler/3372"), new Target("Sócrates", "Brasileiro Sampaio", 5, "https://www.transfermarkt.com/socrates/profil/spieler/117633"), new Target("Kaká", "Ricardo Izecson", 5, "https://www.transfermarkt.com/kaka/profil/spieler/3366"), new Target("Ruud Gullit", "The Black Tulip", 6, "https://www.transfermarkt.com/ruud-gullit/profil/spieler/101045"), new Target("Michael Laudrup", "Michael Laudrup", 6, "https://www.transfermarkt.com/michael-laudrup/profil/spieler/8023"), new Target("Roberto Rivellino", "Rivelino", 7, "https://www.transfermarkt.com/rivellino/profil/spieler/1020"), new Target("Gianni Rivera", "Gianni Rivera", 7, "https://www.transfermarkt.com/gianni-rivera/profil/spieler/145347"), new Target("Frank Lampard", "Super Frank", 7, "https://www.transfermarkt.com/frank-lampard/profil/spieler/3163"), new Target("Youri Djorkaeff", "Youri Raffi", 8, "https://www.transfermarkt.com/youri-djorkaeff/profil/spieler/4"), new Target("Sandro Mazzola", "Sandro Mazzola", 9, "https://www.transfermarkt.com/sandro-mazzola/profil/spieler/145344"), new Target("Carlos Valderrama", "Carlos Alberto Valderrama", 10, "https://www.transfermarkt.com/carlos-valderrama/profil/spieler/88998"), new Target("Juan Román Riquelme", "El Torero", 10, "https://www.transfermarkt.com/juan-roman-riquelme/profil/spieler/3854")
};
var options = new DbContextOptionsBuilder<DraftDatastoreDbContext>().UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=DraftDatastore;Trusted_Connection=True;TrustServerCertificate=True").Options;
await using var db = new DraftDatastoreDbContext(options); var players = await db.Players.Include(player => player.Aliases).Include(player => player.PlayerPositions).ToListAsync(); var cam = await db.Positions.SingleAsync(position => position.Code == "CAM"); var resolved = new List<(Target Target, Player Player)>(); var unresolved = new List<string>();
foreach (var target in targets) { var matches = players.Where(player => Matches(player, target.Lookup)).ToList(); if (matches.Count != 1) unresolved.Add($"{target.Name} ({matches.Count} matches)"); else resolved.Add((target, matches[0])); }
if (unresolved.Count > 0) { Console.Error.WriteLine("No changes were made because these targets were not uniquely resolved:"); foreach (var target in unresolved) Console.Error.WriteLine($"- {target}"); return 1; }
var approvedIds = resolved.Select(item => item.Player.Id).ToHashSet(); var currentEntries = players.Where(player => player.PlayerPositions.Any(position => position.PositionId == cam.Id)).OrderBy(player => player.FullName).ToList(); var removals = currentEntries.Where(player => !approvedIds.Contains(player.Id)).ToList(); var additions = resolved.Where(item => item.Player.PlayerPositions.All(position => position.PositionId != cam.Id)).ToList(); var rankUpdates = resolved.Where(item => item.Player.PlayerPositions.SingleOrDefault(position => position.PositionId == cam.Id)?.OverallRank != item.Target.Rank).ToList(); var linkUpdates = resolved.Where(item => !string.Equals(item.Player.TransfermarktUrl, item.Target.TransfermarktUrl, StringComparison.Ordinal)).ToList();
Console.WriteLine($"Central Attacking Midfielder catalogue review: {resolved.Count} approved players, {currentEntries.Count} current entries."); Console.WriteLine($"Will remove Central Attacking Midfielder from: {(removals.Count == 0 ? "none" : string.Join(", ", removals.Select(player => player.FullName)))}"); Console.WriteLine($"Will add Central Attacking Midfielder to: {(additions.Count == 0 ? "none" : string.Join(", ", additions.Select(item => item.Player.FullName)))}"); Console.WriteLine($"Will set Central Attacking Midfielder-specific ranks for: {(rankUpdates.Count == 0 ? "none" : string.Join(", ", rankUpdates.Select(item => $"{item.Player.FullName} #{item.Target.Rank}")))}"); Console.WriteLine($"Will update Transfermarkt links for: {(linkUpdates.Count == 0 ? "none" : string.Join(", ", linkUpdates.Select(item => item.Player.FullName)))}");
if (!apply) { Console.WriteLine("Dry run complete. Re-run with --apply to save these changes."); return 0; }
await using var transaction = await db.Database.BeginTransactionAsync(); foreach (var player in removals) db.PlayerPositions.Remove(player.PlayerPositions.Single(position => position.PositionId == cam.Id)); foreach (var (target, player) in resolved) { var mapping = player.PlayerPositions.SingleOrDefault(position => position.PositionId == cam.Id); if (mapping is null) { mapping = new PlayerPosition { PlayerId = player.Id, PositionId = cam.Id, IsPrimary = false }; db.PlayerPositions.Add(mapping); } mapping.OverallRank = target.Rank; player.TransfermarktUrl = target.TransfermarktUrl; } await db.SaveChangesAsync(); await transaction.CommitAsync(); Console.WriteLine("Central Attacking Midfielder catalogue, ranks, and Transfermarkt links updated successfully."); return 0;
static bool Matches(Player player, string lookup) => string.Equals(player.FullName, lookup, StringComparison.OrdinalIgnoreCase) || player.Aliases.Any(alias => string.Equals(alias.Alias, lookup, StringComparison.OrdinalIgnoreCase)) || player.FullName.Contains(lookup, StringComparison.OrdinalIgnoreCase) || player.Aliases.Any(alias => alias.Alias.Contains(lookup, StringComparison.OrdinalIgnoreCase));
sealed record Target(string Name, string Lookup, int Rank, string TransfermarktUrl);
